config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :questions do
    resources :answers
  end
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :read, :dashboard           # allow access to dashboard
    else
      can :update, Question do |question|
        question.user == user
      end
      can :destroy, Question do |question|
        question.user == user
      end

      can :update, Answer do |answer|
        answer.user == user
      end
      can :destroy, Answer do |answer|
        answer.user ==   user
      end

      can :create, Question
      can :create, Answer
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers
    mount_uploader :question_image , QuestionImageUploader
    mount_uploader :file_attachment ,QuestionFileUploader
end

app/models/user.rb
class User < ApplicationRecord

  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answers_params)
    @answer.user = current_user
    @answer.save

    redirect_to questions_url
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to questions_url
  end

  private

  def answers_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :forbidden }
      format.xml { render xml: '...', status: :forbidden }
      format.html { redirect_to main_app.root_url, alert: exception.message }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to questions_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
    authorize! :update ,@question
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    authorize! :update ,@question
  end

  # POST /questions or /questions.json
  def create
    @user = current_user
    @question = @user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    authorize! :destory ,@question
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content,:question_image,:file_attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<p>
<%= answer.content %>
<% if can? :delete ,answer %>
<%= link_to 'delete',question_answer_path(answer.question,answer),method: :delete %>
<% end %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
       Welcome ,<%= current_user.email%>
       <%= link_to 'logout',destroy_user_session_path, method: :delete %>
        <% if current_user.admin? %>
          <%= link_to 'Admin Page',rails_admin_path %>
          <% end %>
    <% else %>
       <%= link_to 'sign in', new_user_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
<div>
    <%= form.label :question_image %>
    <%= form.file_field :question_image %>
</div>

<div>
    <%= form.label :file_attachment %>
    <%= form.file_field :file_attachment %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%= flash[:alert] %>
<%= link_to 'New Question', new_question_path %>
<% @questions.each do |question| %>
  <div>
    <h1> <%= question.content %></h1>
    <%= time_ago_in_words(question.created_at)%> ago by <%= question.user.email %>
    
    <% if can? :update,question %>
    <%= link_to 'Edit', edit_question_path(question) %>
    <% end %>
    
    <% if can? :destroy ,question %>
      <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    
    
    <% if question.answers.any? %>
      <h1>Answers</h1>
      <%= render question.answers %>
    <% end %>
    <p> Add a Answer </p>
    <%= form_for([question,question.answers.build]) do |f|%>
      <%= f.text_area :content %>
      <%= submit_tag 'Add'%>
    <% end %>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>
<%= image_tag @question.question_image.url if @question.question_image? %>
<%= link_to 'File Attchment', @question.file_attachment.url if @question.file_attachment? %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>